version: '3.3'
# Для разработки и отладки
services:
  db:
    image: postgres:13.10
    environment:
      - POSTGRES_USER=fast_api_user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data/:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "82:80"

  web:
    build: .
    environment:
      - POSTGRES_USER=fast_api_user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
      - DB_HOST=localhost
      - DB_PORT=5432
    command:
      sh -c "alembic upgrade head &&
             uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - .:/apps/.
    ports:
     - "8000:8000"
    depends_on:
      - db