version: '3.8'

services:
  test_db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=fast_api_user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres_test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - ./pg_data_test/:/var/lib/postgresql/data

  test_web:
    build: .
    env_file:
      - .env
    command:
      sh -c "pytest -v"
    volumes:
      - .:/apps/.
    ports:
     - "8000:8000"
    depends_on:
      test_db:
        condition: service_healthy
