version: '3.8'

services:
  test_db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASS_TEST}
      - POSTGRES_DB=${DB_NAME_TEST}
    ports:
     - "5433:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME_TEST} -U ${DB_USER_TEST}" ]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - ./data/pg_data_test/:/var/lib/postgresql/data

  test_web:
    build: .
    env_file:
      - .env
    command:
      sh -c "pytest -vv"
    depends_on:
      test_db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:6.2
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    command: bash -c "redis-server --requirepass ${REDIS_PASS}"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - ./data/redis_cache/:/data
