version: '3.3'
# Для разработки и отладки
services:
  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=fast_api_user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data/:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "82:80"
