version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}" ]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - ./data/pg_data/:/var/lib/postgresql/data

  web:
    build: .
    env_file:
      - .env
    command:
      sh -c "alembic upgrade head &&
             uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
     - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:6.2
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    command: bash -c "redis-server --requirepass ${REDIS_PASS}"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - ./data/redis_cache/:/data

  celery:
    build: .
    volumes:
      - .:/app
    entrypoint: >
      sh -c "
        celery -A src.celery_conf worker -B --loglevel=info
      "
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    hostname: rabbitmq
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}
    volumes:
      - ./data/rabbitmq/data/:/var/lib/rabbitmq
      - ./data/rabbitmq/logs/:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15692:15692"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 20
