"""add descount

Revision ID: af6cfff85b81
Revises: c7b82af7ce02
Create Date: 2023-08-16 15:39:35.594347

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'af6cfff85b81'
down_revision = 'c7b82af7ce02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'discount')
    # ### end Alembic commands ###
